# Problem 2:
#   Each new term in the Fibonacci sequence is generated by adding 
#   the previous two terms. By starting with 1 and 2, the first 10 
#   terms will be:
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#   By considering the terms in the Fibonacci sequence whose values
#   do not exceed four million, find the sum of the even-valued terms.


# Create initial integer values to store Fibonacci values
fibOne = 1
fibTwo = 2

# Create an integer to continuously add on the next even value
evenSum = 0

# Initiate a loop that continues until either term exceeds 4,000,000
while fibOne <= 4_000_000 and fibTwo <= 4_000_000:
    # Add even terms to the total
    if (fibTwo % 2) == 0:
        evenSum += fibTwo

    # Add both terms into a temporary value, then update the terms
    addFib = fibOne + fibTwo
    fibOne = fibTwo
    fibTwo = addFib

# Output the result to the user
print("The resulting sum of even values is: ")
print(evenSum)